name: 'Nix Shell'
description: 'Run any command you like in a deterministic nix shell on Linux and macOS'
author: '@workflow and @ZenithalHourlyRate'
inputs:
  interpreter:
    required: true
    description: 'Interpreter to use in the nix shell shebang'
    default: 'bash'
  file:
    required: true
    description: 'nix shell file'
    default: 'shell.nix'
  script:
    required: true
    description: 'The actual script to execute in the shell'
branding:
  color: 'blue'
  icon: 'chevron-right'
runs:
  using: 'node12'
  main: 'dist/index.js'
